name: Builds

on:
  push: {}
  pull_request:
    paths-ignore:
      - '.github/**'

jobs:
  buildForAllPlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
         - U.GB
        unityVersion:
          - 2020.3.14f1
        targetPlatform:
          #          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          #          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          #          - iOS # Build an iOS player.
          #          - Android # Build an Android .apk.
          #          - WebGL # WebGL.
          #          - StandaloneWindows # Build a Windows standalone.
          #          - WSAPlayer # Build an Windows Store Apps player.
          #          - PS4 # Build a PS4 Standalone.
          #          - XboxOne # Build a Xbox One Standalone.
          #          - tvOS # Build to Apple's tvOS platform.
          #          - Switch # Build a Nintendo Switch player
    steps:
      #checkout
      - uses: actions/checkout@v2
        with:
          lfs: true
      #Cache
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: | 
            Library-${{ matrix.projectPath }}-
            Library-
      #Build windows
      - uses: ./
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildMethod: ${{secrets.BUILD_METHOD}}
          s3InstallerAccessKey: ${{secrets.S3_ACCESS_KEY}}
          s3InstallerSecretKey: ${{secrets.S3_SECRET_KEY}}
          s3InstallerRegion: ${{secrets.S3_REGION}}
          s3InstallerBucketName: ${{secrets.S3_BUCKET_NAME}}
          serverDevelopmentAddress: ${{secrets.DEVELOPER_ADDRESS}}
          serverProductionAddress: ${{secrets.PRODUCTION_ADDRESS}}
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #Upload
      - uses: actions/upload-artifact@v2
        with:
          name: Build (${{ matrix.targetPlatform }})
          path: ./${{ matrix.projectPath }}/build/build.zip
          retention-days: 14
